In [1]:
import ipywidgets as widgets
import matplotlib
import matplotlib.pyplot as plt
from tensorflow import keras 
import pandas as pd 
from IPython.display import display, clear_output
import time
import tensorflow as tf 
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'  remove warn 
from IPython.display import clear_output
import time 
from statistics import mean 
import statistics 
from statistics import mode 

In [2]:
# load dnn model
load_model = keras.models.load_model('dnn_model')
sub_model = tf.keras.Model(load_model.get_layer(index = 0).output, load_model.get_layer(index = 2).output)

# read the nature of each question
fb_content = pd.read_csv('./Input/fb_content.csv')

def Average(lst): 
    return mean(lst) 

def most_common(List): 
    return(mode(List)) 

In [3]:
fb_content.head()

Q1.9_1  Q1.9_2  Q1.9_3  Q1.10_1  Q1.10_2  Q1.10_3  Q1.10_4  Q1.10_5  \
0       4       4       4        4        4        4        3        3   
1       3       3       3        4        4        4        4        4   
2       3       1       3        5        3        2        4        3   
3       1       1       1        3        3        3        3        1   
4       3       2       5        3        1        1        1        3   

   Q1.10_6  Q1.10_7  ...  Q1.10_9  Q1.10_10  Q1.10_11  Q1.10_12  Q1.10_13  \
0        3        4  ...        4         3         3         3         3   
1        4        4  ...        4         4         4         4         4   
2        2        1  ...        2         5         5         3         5   
3        3        3  ...        3         3         3         3         3   
4        1        1  ...        1         1         1         1         4   

   Q1.10_14  Q1.10_15  Q1.10_16  Q1.10_17  Q1.10_18  
0         3         3         4         3         3  
1         4         4         4         4         4  
2         3         5         3         5         1  
3         3         3         2         3         3  
4         1         3         1         1         1  

[5 rows x 21 columns]

In [10]:
column_name = ["Question_Number", "factor_be_influenced_max", "factor_be_influenced_max_most_common", "factor_be_influenced_min", "factor_be_influenced_min_most_common"]
factor_results = pd.DataFrame(columns = column_name) 
for n in range(1, 4):
    column_name = 'Q1.9_' + str(n)
    print(column_name)
    factor_influence_max_list = []
    factor_influence_min_list = []
    for k in range(0,597):
        base_input_content = fb_content.iloc[k:k+1]
        base_input = sub_model.predict(base_input_content)
        sub_layer = tf.keras.layers.Softmax()
        base_result = sub_layer(base_input).numpy()
        input_content = base_input_content
        for i in range(1,8):
            #TODO: loop column 
            input_content[column_name] = i
            inp = sub_model.predict(input_content)
            sub_layer = tf.keras.layers.Softmax()
            result = sub_layer(inp).numpy()
            difference = result-base_result
            max_index = difference[0].tolist().index(max(difference[0]))
            min_index = difference[0].tolist().index(min(difference[0]))
            max_number = float(max(difference[0]))
            min_number = float(min(difference[0]))
            mean_number = Average(difference[0])
            factor_influence_max_list.append(max_index)
            factor_influence_min_list.append(min_index)
    print("factor_be_influenced_max", max(factor_influence_max_list))
    print("factor_be_influenced_max_most_common", most_common((factor_influence_max_list)))
    print("factor_be_influenced_min", min(factor_influence_min_list))
    print("factor_be_influenced_min_most_common", most_common(factor_influence_min_list))
    factor_list = [column_name, max(factor_influence_max_list),most_common((factor_influence_max_list)),min(factor_influence_min_list), most_common(factor_influence_min_list)]
    factor_result_series = pd.Series(factor_list, index = factor_results.columns)
    print(factor_result_series)
    factor_results = factor_results.append(factor_result_series, ignore_index = True)
today = time.strftime("%Y-%m-%d")
file_name = today + '_factor_results' + '.csv'
factor_results.to_csv(file_name)
#             print("Input %d:"%i),
#             print(result[0])
#             print("Diff: "),
#             print(difference[0])
#             print("\nFactor %s Factor %s"%(max_index, min_index))
#             print("Max: %.3f Min: %.3f Mean: %.3f\n"%(max_number, min_number, mean_number))
#         time.sleep(10)
#         clear_output()

Question: Q1.9_1
Input 1:
[0.40460956 0.1488476  0.1488476  0.1488476  0.14884765]
Diff: 
[0. 0. 0. 0. 0.]

Factor 0 Factor 0
Max: 0.000 Min: 0.000 Mean: 0.000

factor_be_influenced_max 0
Input 1:
[0.40460956 0.1488476  0.1488476  0.1488476  0.14884765]
Diff: 
[0. 0. 0. 0. 0.]

Factor 0 Factor 0
Max: 0.000 Min: 0.000 Mean: 0.000

factor_be_influenced_max 0
factor_be_influenced_max_most_common 0
factor_be_influenced_min 0
factor_be_influenced_min_most_common 0
Question_Number                         Q1.9_1
factor_be_influenced_max                     0
factor_be_influenced_max_most_common         0
factor_be_influenced_min                     0
factor_be_influenced_min_most_common         0
dtype: object
